Repository OnlyOTP/OnlyOTP, pull requests merged in 2022-10, with the labels that each got.

#15 Added Clear and Remove to delete OTPs from storage #14
  OnlyOtp.Storage/OnlyOtp.Storage.Abstractions/IOtpStorage.cs
  OnlyOtp.Storage/OnlyOtp.Storage.Abstractions/OnlyOtp.Storage.Abstractions.csproj
  OnlyOtp.Storage/OnlyOtp.Storage.InMemory/InMemoryOtpStorage.cs
  OnlyOtp.Storage/OnlyOtp.Storage.InMemory/OnlyOtp.Storage.InMemory.csproj
  OnlyOtp.Storage/OnlyOtp.Storage.SqlServer/OnlyOtp.Storage.SqlServer.csproj
  OnlyOtp.Storage/OnlyOtp.Storage.SqlServer/SqlServerOtpStorage.cs
  OnlyOtp.Tests/OnlyOtp.Tests.csproj
  OnlyOtp.Tests/Storage/InMemoryStorageTests.cs
  OnlyOtp.Tests/Storage/SqlServerOtpStorageTests.cs
  OnlyOtp/OnlyOtp.csproj
Labels: hacktoberfest

#16 Updated docs about Clear
  README.md
Labels: HACKTOBERFEST-ACCEPTED

#19 Added OTP removal into engine. Fixes #18.
  OnlyOtp.Tests/OtpTests.cs
  OnlyOtp/IOtp.cs
  OnlyOtp/Otp.cs
Labels: enhancement, hacktoberfest, HACKTOBERFEST-ACCEPTED

#21 Update docs about clear storage engine
  README.md
Labels: documentation, hacktoberfest, HACKTOBERFEST-ACCEPTED

#26 Updated OnlyOTP to 1.1.1
  OnlyOtp.Storage/OnlyOtp.Storage.Abstractions/OnlyOtp.Storage.Abstractions.csproj
  OnlyOtp/OnlyOtp.csproj
Labels: hacktoberfest, HACKTOBERFEST-ACCEPTED

#27 Updated OnlyOTP.Storage.InMemory to 1.1.1
  OnlyOtp.Storage/OnlyOtp.Storage.InMemory/OnlyOtp.Storage.InMemory.csproj
Labels: hacktoberfest, HACKTOBERFEST-ACCEPTED

#28 Update OnlyOtp.Storage.SqlServer.csproj
  OnlyOtp.Storage/OnlyOtp.Storage.SqlServer/OnlyOtp.Storage.SqlServer.csproj
Labels: hacktoberfest, HACKTOBERFEST-ACCEPTED

#29 Update OnlyOtp.Storage.Abstractions.csproj
  OnlyOtp.Storage/OnlyOtp.Storage.Abstractions/OnlyOtp.Storage.Abstractions.csproj
Labels: hacktoberfest, HACKTOBERFEST-ACCEPTED
